baseUrl = "https://peterevans.dev/"
languageCode = "en-us"
title = "The blog of Peter Evans"
theme = "vela"
[taxonomies]
    tag = "tags"
pygmentsCodeFences = true
pygmentsUseClasses = true
canonifyURLs = true

[params]
    author = "Peter Evans"
    description = "Thoughts and notes on software engineering, architecture and testing."
    keywords = ["Peter Evans", "software engineering", "software architecture", "software testing"]
